# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2021-01-14 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=11.1, max_digits=10),
        ),
    ]
